### PR TITLE
Update plotting scripts

### PR DESCRIPTION
**Pull request by vincekurtz**
Fixes the plotting scripts for use with the new directory structure (#2). 

- Removes legacy scripts that we used in the solver development process, and are unlikely to be useful moving forward
- Updates the remaining scripts to match the new directory structure

This PR builds on #2, review that first. Towards #5.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8)

### CODE REVIEW

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @vincekurtz)

___
*[`scripts/compare_convergence.py` line 8 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8#-NfleS1B-sp-d5cKAZnv:-NfleS1B-sp-d5cKAZnw:b41x29g) ([raw file](https://github.com/ToyotaResearchInstitute/idto/blob/5f09ff782b14b3092f733dce6cdf76b71b2fbbb2/scripts/compare_convergence.py#L8)):*
> ```Python
> # These log files should be manually copied from solver_stats.csv first. 
> #
> # This script must be run from the "idto/" directory. 
> ```

consider adding command line example? and briefly document expeted outcome?
___
*[`scripts/plot_convergence_data.py` line 8 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8#-Nflehsl5h0lZD00P-rq:-Nflehsl5h0lZD00P-rr:bwxftkh) ([raw file](https://github.com/ToyotaResearchInstitute/idto/blob/5f09ff782b14b3092f733dce6cdf76b71b2fbbb2/scripts/plot_convergence_data.py#L8)):*
> ```Python
> # example (see example_base.h).
> #
> # This script must be run from the "idto/" directory. 
> ```

ditto, consider adding command line example. 
Maybe not a bad idea to update README with a specific example showing how to run these scripts

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @amcastro-tri)

___
*[`scripts/compare_convergence.py` line 8 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8#-NfleS1B-sp-d5cKAZnv:-Nflq32H1X-0o4BI-Wg1:bu3usn5) ([raw file](https://github.com/ToyotaResearchInstitute/idto/blob/5f09ff782b14b3092f733dce6cdf76b71b2fbbb2/scripts/compare_convergence.py#L8)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

consider adding command line example? and briefly document expeted outcome?
</blockquote></details>

Added a readme with example usage and more details
___
*[`scripts/plot_convergence_data.py` line 8 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8#-Nflehsl5h0lZD00P-rq:-Nflq7lp1uxlTx5YUCVa:b-tm1i0d) ([raw file](https://github.com/ToyotaResearchInstitute/idto/blob/5f09ff782b14b3092f733dce6cdf76b71b2fbbb2/scripts/plot_convergence_data.py#L8)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, consider adding command line example. 
Maybe not a bad idea to update README with a specific example showing how to run these scripts
</blockquote></details>

Good idea on the README. Added a separate one in this directory

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @vincekurtz)

**Review by amcastro-tri — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vincekurtz)

**Pull request merged**
