### PR TITLE
Improve linting and test coverage

### PR DESCRIPTION
**Pull request by vincekurtz**
- Adds some basic cpp linting, adopted from Drake
- Adds a `.clang-format` file so vscode's autoformatting matches the Drake style
- Enables lint checks
- Runs each of the examples as a test

This builds on #2, so wait for that to go in first.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/4)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri, pending resolution of #2 

looks like reviewable works!

> *[Reviewable](https://reviewable.io/reviews/toyotaresearchinstitute/idto/4#-:-NfSmr--2FSfqBpK93S6:b-ozkq4x)* status: 0 of 137 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
ok, lets merge that first. Otherwise I can't spot the diffs

> *[Reviewable](https://reviewable.io/reviews/toyotaresearchinstitute/idto/4#-:-NflSNmk2-BfFLieFO0o:bt2v45n)* status: 0 of 137 files reviewed, all discussions resolved

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toyotaresearchinstitute/idto/4)* status: 134 of 137 files reviewed, 3 unresolved discussions (waiting on @amcastro-tri)

___
*[`.clang-format` line 4 at r2](https://reviewable.io/reviews/toyotaresearchinstitute/idto/4#-NflbLiOBKyqAZktvLru:-NfmZayj7JuH64DwTSmR:b-ei59qz) ([raw file](https://github.com/toyotaresearchinstitute/idto/blob/444c878946fd303a765d588b8b2f2fbae705d3f9/.clang-format#L4)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

how did you generate this @vincekurtz?
Is this the one from Drake? if so plese  add reference and comments where things differ
</blockquote></details>

yup, done
___
*[`tools/lint/cpplint.bzl` line 1 at r2](https://reviewable.io/reviews/toyotaresearchinstitute/idto/4#-NflcIKH6MdBPY9OSA-a:-Nfm_6N02J9AmeDNBCA-:b-896fix) ([raw file](https://github.com/toyotaresearchinstitute/idto/blob/444c878946fd303a765d588b8b2f2fbae705d3f9/tools/lint/cpplint.bzl#L1)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is this copied from Drake? add reference
</blockquote></details>

Done.
___
*[`tools/lint/lint.bzl` line 1 at r2](https://reviewable.io/reviews/toyotaresearchinstitute/idto/4#-NflcOaXCg3ZR6-M__fe:-Nfm_VbtAtIN0HjN21jA:b-896fix) ([raw file](https://github.com/toyotaresearchinstitute/idto/blob/444c878946fd303a765d588b8b2f2fbae705d3f9/tools/lint/lint.bzl#L1)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

reference to Drake if appropriate
</blockquote></details>

Done.

**Review by amcastro-tri — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toyotaresearchinstitute/idto/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vincekurtz)

**Pull request merged**
