### PR TITLE
Replace calls to deprecated damping() methods

### PR DESCRIPTION
**Pull request by joemasterjohn**
Replaced newly deprecated APIs from RobotLocomotion/drake#20947.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/26)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
@vincekurtz @amcastro-tri looks like I don't have permission to assign a reviewer here, so I'll pass it to you for your disposition.

> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/26#-:-NrrKP42C9s82BBpdndK:bks8rg0)* status: 0 of 1 files reviewed, all discussions resolved

**Review by vincekurtz — CHANGES_REQUESTED** [review]
Hi Joe!! I'll go ahead and self-assign this one.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/26#-:-NrrTzlJE6UtgktQOmsO:by4oxsy)* status: all files reviewed, 1 unresolved discussion (waiting on @joemasterjohn)

___
*[`optimizer/trajectory_optimizer.cc` line 60 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/26#-NrrU4J877eU9ApmXnsT:-NrrU4J877eU9ApmXnsU:bmw36br) ([raw file](https://github.com/ToyotaResearchInstitute/idto/blob/c985fe0a256f26d39b7f77066f011fbcc55112da/optimizer/trajectory_optimizer.cc#L60)):*
> ```cpp
>     const int velocity_start = joint.velocity_start();
>     const int nv = joint.num_velocities();
>     joint_damping_.segment(velocity_start, nv) = joint.default_damping_vector();
> ```

This isn't defined in drake `v1.25.0`, which is the current default version.

We should bump the default version in `WORKSPACE` to whatever the latest version that includes this change is.

**Review by joemasterjohn — COMMENTED** [review]
Hey Vince! :wave: 

> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/26#-:-Nrv288r-ZU3LBQ8B5Dx:b-cwcd8a)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @vincekurtz)

___
*[`optimizer/trajectory_optimizer.cc` line 60 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/26#-NrrU4J877eU9ApmXnsT:-Nrv2BQr-OAJmlOwSBVl:b-mtd778) ([raw file](https://github.com/ToyotaResearchInstitute/idto/blob/c985fe0a256f26d39b7f77066f011fbcc55112da/optimizer/trajectory_optimizer.cc#L60)):*
<details><summary><i>Previously, vincekurtz (Vince Kurtz) wrote…</i></summary><blockquote>

This isn't defined in drake `v1.25.0`, which is the current default version.

We should bump the default version in `WORKSPACE` to whatever the latest version that includes this change is.
</blockquote></details>

Ah yes. This deprecation came from a very recent commit (yesterday) so it won't hit a release until mid-March. I've updated the pinned Drake version to the last commit from yesterday 2024-02-29 and bumped to C++20 support (required for the updated Drake build). I can come back and bump to 1.27.0 when it lands in a few weeks so you'll be back to a stable release.

BTW I forgot to give you context: I'm just making this change because Anzu master now has deprecation warnings I introduced that originate from the idto dependency.

**Review by vincekurtz — APPROVED** [review]
Awesome, thanks Joe! :lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/idto/26#-:-NrvBVn78lPatDO4yKWR:b-9x59dm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @joemasterjohn)

**Comment by joemasterjohn** [comment]
Thanks Vince!

**Pull request merged**
